import type {
  BiomeType,
  TerrainParams,
  WaterParams,
  FeatureConfig,
  AtmosphereParams,
  ColorPalette,
  CameraParams,
  ParticleType,
} from "./types";

export interface BiomeDefinition {
  terrain: TerrainParams;
  water: WaterParams | null;
  features: FeatureConfig[];
  atmosphere: AtmosphereParams;
  particles: ParticleType;
  palette: ColorPalette;
  camera: CameraParams;
  names: string[];
}

const BASE_SEED = () => Math.floor(Math.random() * 100000);

export const BIOME_DEFINITIONS: Record<BiomeType, BiomeDefinition> = {
  forest: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 6,
      persistence: 0.45,
      lacunarity: 2.1,
      amplitude: 8,
      frequency: 0.012,
      plateauFactor: 0,
      ridgeFactor: 0,
      erosion: 0.3,
    },
    water: { level: -1.5, color: "#1a5276", opacity: 0.7, speed: 0.3, distortion: 0.4, isLava: false },
    features: [
      { type: "tree_pine", density: 0.35, minScale: 0.7, maxScale: 1.8 },
      { type: "tree_oak", density: 0.2, minScale: 0.8, maxScale: 2.0 },
      { type: "rock", density: 0.1, minScale: 0.3, maxScale: 1.0 },
      { type: "flower", density: 0.15, minScale: 0.2, maxScale: 0.5 },
      { type: "mushroom", density: 0.05, minScale: 0.2, maxScale: 0.6 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [50, 80, 30],
      skyTurbidity: 8,
      skyRayleigh: 1.5,
      fogDensity: 0.015,
      fogColor: "#8fbc8f",
      cloudCoverage: 0.3,
      starDensity: 0,
    },
    particles: "fireflies",
    palette: {
      terrain: ["#2d1b0e", "#3a5f0b", "#4a7c1f", "#6b8e23", "#8fbc8f"],
      sky: "#87ceeb",
      ambient: "#4a6741",
      sunColor: "#fff5e6",
      sunIntensity: 1.8,
      ambientIntensity: 0.5,
      accent: "#228b22",
    },
    camera: { position: [25, 18, 25], target: [0, 0, 0], fov: 55 },
    names: ["Whispering Woods", "Emerald Canopy", "The Verdant Expanse", "Sylvan Glade"],
  },

  desert: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 4,
      persistence: 0.35,
      lacunarity: 2.5,
      amplitude: 12,
      frequency: 0.008,
      plateauFactor: 0.3,
      ridgeFactor: 0.1,
      erosion: 0.6,
    },
    water: null,
    features: [
      { type: "cactus", density: 0.06, minScale: 0.5, maxScale: 1.5 },
      { type: "rock", density: 0.08, minScale: 0.5, maxScale: 2.0 },
      { type: "boulder", density: 0.04, minScale: 1.0, maxScale: 3.0 },
      { type: "ruin", density: 0.02, minScale: 0.8, maxScale: 1.5 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [60, 100, 20],
      skyTurbidity: 20,
      skyRayleigh: 0.5,
      fogDensity: 0.005,
      fogColor: "#d4a574",
      cloudCoverage: 0.05,
      starDensity: 0,
    },
    particles: "dust",
    palette: {
      terrain: ["#8b6914", "#c2a04e", "#d4a574", "#e8c99b", "#f5deb3"],
      sky: "#e8d5a3",
      ambient: "#d4a574",
      sunColor: "#ffe4b5",
      sunIntensity: 2.5,
      ambientIntensity: 0.7,
      accent: "#cd853f",
    },
    camera: { position: [30, 20, 30], target: [0, 2, 0], fov: 60 },
    names: ["Scorched Dunes", "The Amber Wastes", "Sunfire Expanse", "Dust Sea"],
  },

  arctic: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.4,
      lacunarity: 2.2,
      amplitude: 10,
      frequency: 0.01,
      plateauFactor: 0.2,
      ridgeFactor: 0.15,
      erosion: 0.2,
    },
    water: { level: -2, color: "#1a3a4a", opacity: 0.6, speed: 0.1, distortion: 0.2, isLava: false },
    features: [
      { type: "ice_spike", density: 0.12, minScale: 0.5, maxScale: 2.5 },
      { type: "rock", density: 0.08, minScale: 0.4, maxScale: 1.5 },
      { type: "boulder", density: 0.05, minScale: 1.0, maxScale: 2.5 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "snowy",
      sunPosition: [30, 30, 50],
      skyTurbidity: 3,
      skyRayleigh: 2.0,
      fogDensity: 0.02,
      fogColor: "#b0c4de",
      cloudCoverage: 0.6,
      starDensity: 0,
    },
    particles: "snow",
    palette: {
      terrain: ["#4a6a7a", "#8ab4c4", "#b0d4e4", "#d4eaf4", "#f0f8ff"],
      sky: "#b0c4de",
      ambient: "#87ceeb",
      sunColor: "#e6f0ff",
      sunIntensity: 1.2,
      ambientIntensity: 0.6,
      accent: "#00ced1",
    },
    camera: { position: [25, 15, 25], target: [0, 0, 0], fov: 55 },
    names: ["Frozen Reach", "The Crystal Tundra", "Glacial Expanse", "Frostfall"],
  },

  ocean: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 4,
      persistence: 0.3,
      lacunarity: 2.0,
      amplitude: 4,
      frequency: 0.015,
      plateauFactor: 0.5,
      ridgeFactor: 0,
      erosion: 0.5,
    },
    water: { level: 1.5, color: "#006994", opacity: 0.75, speed: 0.5, distortion: 0.6, isLava: false },
    features: [
      { type: "coral", density: 0.2, minScale: 0.3, maxScale: 1.2 },
      { type: "rock", density: 0.1, minScale: 0.5, maxScale: 2.0 },
      { type: "pillar", density: 0.03, minScale: 1.0, maxScale: 3.0 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [40, 70, 40],
      skyTurbidity: 10,
      skyRayleigh: 2.5,
      fogDensity: 0.025,
      fogColor: "#1a5276",
      cloudCoverage: 0.4,
      starDensity: 0,
    },
    particles: "dust",
    palette: {
      terrain: ["#1a3a4a", "#1a5276", "#2980b9", "#5dade2", "#aed6f1"],
      sky: "#5dade2",
      ambient: "#2980b9",
      sunColor: "#fff8dc",
      sunIntensity: 1.6,
      ambientIntensity: 0.5,
      accent: "#00bcd4",
    },
    camera: { position: [20, 12, 20], target: [0, 0, 0], fov: 60 },
    names: ["The Abyssal Deep", "Coral Kingdoms", "Tidewater Realm", "Sapphire Sea"],
  },

  volcanic: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.5,
      lacunarity: 2.3,
      amplitude: 15,
      frequency: 0.01,
      plateauFactor: 0.1,
      ridgeFactor: 0.4,
      erosion: 0.15,
    },
    water: { level: -3, color: "#ff4500", opacity: 0.85, speed: 0.15, distortion: 0.3, isLava: true },
    features: [
      { type: "lava_rock", density: 0.15, minScale: 0.5, maxScale: 2.0 },
      { type: "rock", density: 0.12, minScale: 0.4, maxScale: 1.8 },
      { type: "pillar", density: 0.05, minScale: 1.0, maxScale: 4.0 },
    ],
    atmosphere: {
      timeOfDay: "dusk",
      weather: "foggy",
      sunPosition: [20, 20, 40],
      skyTurbidity: 25,
      skyRayleigh: 0.3,
      fogDensity: 0.03,
      fogColor: "#2a0a0a",
      cloudCoverage: 0.7,
      starDensity: 0,
    },
    particles: "embers",
    palette: {
      terrain: ["#1a0a0a", "#3d1c02", "#5c2e0e", "#8b4513", "#2a0a0a"],
      sky: "#1a0505",
      ambient: "#4a1a0a",
      sunColor: "#ff6347",
      sunIntensity: 1.0,
      ambientIntensity: 0.3,
      accent: "#ff4500",
    },
    camera: { position: [28, 22, 28], target: [0, 3, 0], fov: 55 },
    names: ["Infernal Caldera", "The Molten Forge", "Ashfire Peaks", "Ember Wastes"],
  },

  alien: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 7,
      persistence: 0.5,
      lacunarity: 2.4,
      amplitude: 10,
      frequency: 0.013,
      plateauFactor: 0.15,
      ridgeFactor: 0.2,
      erosion: 0.1,
    },
    water: { level: -1, color: "#4a0080", opacity: 0.6, speed: 0.4, distortion: 0.8, isLava: false },
    features: [
      { type: "mushroom_giant", density: 0.12, minScale: 1.0, maxScale: 3.0, emissive: true },
      { type: "mushroom", density: 0.2, minScale: 0.3, maxScale: 1.0, emissive: true },
      { type: "crystal", density: 0.1, minScale: 0.5, maxScale: 2.0, emissive: true },
      { type: "pillar", density: 0.04, minScale: 1.5, maxScale: 4.0 },
    ],
    atmosphere: {
      timeOfDay: "dusk",
      weather: "foggy",
      sunPosition: [30, 40, 60],
      skyTurbidity: 15,
      skyRayleigh: 4.0,
      fogDensity: 0.02,
      fogColor: "#1a0033",
      cloudCoverage: 0.3,
      starDensity: 2000,
    },
    particles: "spores",
    palette: {
      terrain: ["#1a0033", "#2d1b4e", "#4a2d6e", "#6b3fa0", "#8b5cf6"],
      sky: "#0a0020",
      ambient: "#4a0080",
      sunColor: "#da70d6",
      sunIntensity: 1.2,
      ambientIntensity: 0.4,
      accent: "#8b5cf6",
    },
    camera: { position: [22, 16, 22], target: [0, 1, 0], fov: 58 },
    names: ["Xenoflora Expanse", "The Violet Wastes", "Spore Fields", "Otherworld"],
  },

  crystal: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.45,
      lacunarity: 2.6,
      amplitude: 8,
      frequency: 0.011,
      plateauFactor: 0.25,
      ridgeFactor: 0.3,
      erosion: 0.05,
    },
    water: { level: -2, color: "#00e5ff", opacity: 0.5, speed: 0.2, distortion: 0.3, isLava: false },
    features: [
      { type: "crystal_cluster", density: 0.2, minScale: 0.5, maxScale: 2.5, emissive: true },
      { type: "crystal", density: 0.25, minScale: 0.3, maxScale: 1.8, emissive: true },
      { type: "pillar", density: 0.06, minScale: 1.5, maxScale: 5.0, colorOverride: "#00e5ff", emissive: true },
      { type: "rock", density: 0.08, minScale: 0.3, maxScale: 1.0 },
    ],
    atmosphere: {
      timeOfDay: "night",
      weather: "clear",
      sunPosition: [20, 30, 50],
      skyTurbidity: 2,
      skyRayleigh: 1.0,
      fogDensity: 0.01,
      fogColor: "#0a1a2a",
      cloudCoverage: 0.1,
      starDensity: 4000,
    },
    particles: "fireflies",
    palette: {
      terrain: ["#0a1a2a", "#1a2a4a", "#2a3a5a", "#3a5a8a", "#4a7aba"],
      sky: "#050a15",
      ambient: "#1a3a5a",
      sunColor: "#00e5ff",
      sunIntensity: 0.8,
      ambientIntensity: 0.35,
      accent: "#00e5ff",
    },
    camera: { position: [20, 14, 20], target: [0, 1, 0], fov: 55 },
    names: ["Crystal Caverns", "The Prismatic Depths", "Gemstone Hollow", "Luminite Reach"],
  },

  cyberpunk: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 3,
      persistence: 0.3,
      lacunarity: 2.0,
      amplitude: 3,
      frequency: 0.02,
      plateauFactor: 0.7,
      ridgeFactor: 0,
      erosion: 0.8,
    },
    water: { level: -0.5, color: "#0a0a2e", opacity: 0.8, speed: 0.1, distortion: 0.15, isLava: false },
    features: [
      { type: "building", density: 0.2, minScale: 1.0, maxScale: 5.0 },
      { type: "tower", density: 0.08, minScale: 2.0, maxScale: 8.0, emissive: true },
      { type: "pillar", density: 0.06, minScale: 0.5, maxScale: 2.0, colorOverride: "#ff00ff", emissive: true },
    ],
    atmosphere: {
      timeOfDay: "night",
      weather: "foggy",
      sunPosition: [10, 10, 50],
      skyTurbidity: 30,
      skyRayleigh: 0.2,
      fogDensity: 0.035,
      fogColor: "#0a0a1e",
      cloudCoverage: 0.8,
      starDensity: 500,
    },
    particles: "rain",
    palette: {
      terrain: ["#0a0a1e", "#1a1a2e", "#0a0a2e", "#1a0a2e", "#0a1a2e"],
      sky: "#050510",
      ambient: "#1a0a2e",
      sunColor: "#ff00ff",
      sunIntensity: 0.5,
      ambientIntensity: 0.25,
      accent: "#00ffff",
    },
    camera: { position: [20, 18, 20], target: [0, 4, 0], fov: 60 },
    names: ["Neon District", "The Grid", "Synth City", "Chrome Sprawl"],
  },

  meadow: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 4,
      persistence: 0.35,
      lacunarity: 2.0,
      amplitude: 4,
      frequency: 0.01,
      plateauFactor: 0.1,
      ridgeFactor: 0,
      erosion: 0.4,
    },
    water: { level: -1, color: "#4a90a4", opacity: 0.6, speed: 0.25, distortion: 0.3, isLava: false },
    features: [
      { type: "flower", density: 0.35, minScale: 0.15, maxScale: 0.5 },
      { type: "tree_oak", density: 0.06, minScale: 1.0, maxScale: 2.5 },
      { type: "rock", density: 0.05, minScale: 0.2, maxScale: 0.8 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [50, 90, 30],
      skyTurbidity: 6,
      skyRayleigh: 2.0,
      fogDensity: 0.008,
      fogColor: "#90ee90",
      cloudCoverage: 0.25,
      starDensity: 0,
    },
    particles: "fireflies",
    palette: {
      terrain: ["#4a3520", "#5a8a2a", "#7cba3a", "#9acd32", "#b8e060"],
      sky: "#87ceeb",
      ambient: "#7cba3a",
      sunColor: "#fff8dc",
      sunIntensity: 2.0,
      ambientIntensity: 0.6,
      accent: "#ff69b4",
    },
    camera: { position: [18, 10, 18], target: [0, 0, 0], fov: 60 },
    names: ["Sunlit Meadow", "The Golden Fields", "Wildflower Vale", "Pastoral Glade"],
  },

  swamp: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.4,
      lacunarity: 2.1,
      amplitude: 5,
      frequency: 0.013,
      plateauFactor: 0.4,
      ridgeFactor: 0,
      erosion: 0.5,
    },
    water: { level: 0.5, color: "#2d4a1a", opacity: 0.8, speed: 0.05, distortion: 0.15, isLava: false },
    features: [
      { type: "tree_dead", density: 0.15, minScale: 0.8, maxScale: 2.0 },
      { type: "mushroom", density: 0.15, minScale: 0.3, maxScale: 1.0, emissive: true },
      { type: "rock", density: 0.1, minScale: 0.3, maxScale: 1.2 },
    ],
    atmosphere: {
      timeOfDay: "dusk",
      weather: "foggy",
      sunPosition: [20, 25, 40],
      skyTurbidity: 18,
      skyRayleigh: 1.0,
      fogDensity: 0.04,
      fogColor: "#2a3a1a",
      cloudCoverage: 0.7,
      starDensity: 0,
    },
    particles: "spores",
    palette: {
      terrain: ["#1a2a0a", "#2a3a1a", "#3a4a2a", "#4a5a3a", "#3a4a2a"],
      sky: "#3a4a2a",
      ambient: "#2a3a1a",
      sunColor: "#b8a040",
      sunIntensity: 0.8,
      ambientIntensity: 0.3,
      accent: "#7fff00",
    },
    camera: { position: [20, 12, 20], target: [0, 0, 0], fov: 58 },
    names: ["Murky Fen", "The Rotting Bog", "Miasma Marsh", "Gloomwater"],
  },

  canyon: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 6,
      persistence: 0.5,
      lacunarity: 2.4,
      amplitude: 18,
      frequency: 0.009,
      plateauFactor: 0.35,
      ridgeFactor: 0.5,
      erosion: 0.3,
    },
    water: { level: -6, color: "#2a6a8a", opacity: 0.7, speed: 0.4, distortion: 0.3, isLava: false },
    features: [
      { type: "rock", density: 0.12, minScale: 0.5, maxScale: 2.0 },
      { type: "boulder", density: 0.08, minScale: 1.5, maxScale: 4.0 },
      { type: "pillar", density: 0.04, minScale: 2.0, maxScale: 6.0 },
      { type: "cactus", density: 0.03, minScale: 0.4, maxScale: 1.2 },
    ],
    atmosphere: {
      timeOfDay: "dusk",
      weather: "clear",
      sunPosition: [40, 40, 60],
      skyTurbidity: 12,
      skyRayleigh: 1.0,
      fogDensity: 0.01,
      fogColor: "#8b6914",
      cloudCoverage: 0.15,
      starDensity: 0,
    },
    particles: "dust",
    palette: {
      terrain: ["#5c2e0e", "#8b4513", "#a0522d", "#cd853f", "#d2b48c"],
      sky: "#cd853f",
      ambient: "#8b4513",
      sunColor: "#ffa07a",
      sunIntensity: 1.8,
      ambientIntensity: 0.45,
      accent: "#ff6347",
    },
    camera: { position: [30, 25, 30], target: [0, 0, 0], fov: 55 },
    names: ["Redstone Canyon", "The Shattered Gorge", "Windcarved Ravine", "Dustwall Pass"],
  },

  space: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.45,
      lacunarity: 2.3,
      amplitude: 6,
      frequency: 0.014,
      plateauFactor: 0.2,
      ridgeFactor: 0.15,
      erosion: 0.2,
    },
    water: null,
    features: [
      { type: "crystal", density: 0.1, minScale: 0.3, maxScale: 1.5, emissive: true },
      { type: "rock", density: 0.12, minScale: 0.5, maxScale: 2.0 },
      { type: "floating_island", density: 0.04, minScale: 2.0, maxScale: 5.0 },
      { type: "pillar", density: 0.03, minScale: 1.0, maxScale: 3.0 },
    ],
    atmosphere: {
      timeOfDay: "night",
      weather: "clear",
      sunPosition: [60, 20, 60],
      skyTurbidity: 1,
      skyRayleigh: 0.1,
      fogDensity: 0.005,
      fogColor: "#050510",
      cloudCoverage: 0,
      starDensity: 6000,
    },
    particles: "dust",
    palette: {
      terrain: ["#1a1a2e", "#16213e", "#0f3460", "#533483", "#1a1a2e"],
      sky: "#020210",
      ambient: "#1a1a3e",
      sunColor: "#c0c0ff",
      sunIntensity: 0.6,
      ambientIntensity: 0.2,
      accent: "#c084fc",
    },
    camera: { position: [22, 16, 22], target: [0, 1, 0], fov: 60 },
    names: ["Lunar Expanse", "The Void Plateau", "Astral Wastes", "Starfall Basin"],
  },

  tropical: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 5,
      persistence: 0.4,
      lacunarity: 2.1,
      amplitude: 7,
      frequency: 0.011,
      plateauFactor: 0.15,
      ridgeFactor: 0.05,
      erosion: 0.35,
    },
    water: { level: -0.5, color: "#00a8a8", opacity: 0.65, speed: 0.35, distortion: 0.5, isLava: false },
    features: [
      { type: "tree_palm", density: 0.2, minScale: 0.8, maxScale: 2.0 },
      { type: "flower", density: 0.2, minScale: 0.2, maxScale: 0.6 },
      { type: "rock", density: 0.06, minScale: 0.3, maxScale: 1.0 },
      { type: "coral", density: 0.05, minScale: 0.3, maxScale: 0.8 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [50, 85, 25],
      skyTurbidity: 10,
      skyRayleigh: 2.0,
      fogDensity: 0.01,
      fogColor: "#87ceeb",
      cloudCoverage: 0.35,
      starDensity: 0,
    },
    particles: "fireflies",
    palette: {
      terrain: ["#c2a04e", "#5a8a2a", "#3cb371", "#2e8b57", "#006400"],
      sky: "#00bfff",
      ambient: "#3cb371",
      sunColor: "#fff8dc",
      sunIntensity: 2.2,
      ambientIntensity: 0.55,
      accent: "#ff6347",
    },
    camera: { position: [22, 14, 22], target: [0, 0, 0], fov: 58 },
    names: ["Paradise Cove", "The Emerald Isles", "Sunshore Haven", "Tropic Bloom"],
  },

  mountains: {
    terrain: {
      seed: BASE_SEED(),
      octaves: 7,
      persistence: 0.52,
      lacunarity: 2.5,
      amplitude: 22,
      frequency: 0.008,
      plateauFactor: 0.1,
      ridgeFactor: 0.6,
      erosion: 0.15,
    },
    water: { level: -5, color: "#2a5a7a", opacity: 0.7, speed: 0.3, distortion: 0.4, isLava: false },
    features: [
      { type: "tree_pine", density: 0.15, minScale: 0.6, maxScale: 1.5 },
      { type: "rock", density: 0.15, minScale: 0.5, maxScale: 2.0 },
      { type: "boulder", density: 0.1, minScale: 1.0, maxScale: 3.5 },
    ],
    atmosphere: {
      timeOfDay: "day",
      weather: "clear",
      sunPosition: [40, 60, 40],
      skyTurbidity: 5,
      skyRayleigh: 2.5,
      fogDensity: 0.012,
      fogColor: "#a0b0c0",
      cloudCoverage: 0.4,
      starDensity: 0,
    },
    particles: "dust",
    palette: {
      terrain: ["#3a3a3a", "#5a5a5a", "#7a7a6a", "#a0a090", "#e8e8e8"],
      sky: "#6a8fba",
      ambient: "#7a8a9a",
      sunColor: "#fff5e6",
      sunIntensity: 1.6,
      ambientIntensity: 0.45,
      accent: "#4682b4",
    },
    camera: { position: [35, 28, 35], target: [0, 5, 0], fov: 50 },
    names: ["The Iron Peaks", "Stormcrest Range", "Skyward Summits", "Granite Throne"],
  },
};
